export const UPDATE_ANALYSIS_FORM = 'UPDATE_ANALYSIS_FORM';
export const UPDATE_ENTITY = 'UPDATE_ENTITY';
export const REQUEST_IN_PROGRESS = 'REQUEST_IN_PROGRESS';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const UPDATE_ANALYSIS = 'UPDATE_ANALYSIS';