"""empty message

Revision ID: 0b10b416029f
Revises: e102cfab9558
Create Date: 2017-11-07 22:34:35.556690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b10b416029f'
down_revision = 'e102cfab9558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('address', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity', 'address')
    # ### end Alembic commands ###
