"""empty message

Revision ID: 5156dde46a9a
Revises: 0b10b416029f
Create Date: 2017-11-07 23:09:35.105679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5156dde46a9a'
down_revision = '0b10b416029f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('current_liability', sa.Float(), nullable=True))
    op.drop_column('analysis', 'passive_liability')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('passive_liability', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('analysis', 'current_liability')
    # ### end Alembic commands ###
