"""empty message

Revision ID: a2e230655523
Revises: d0a4996f1eb0
Create Date: 2017-11-05 19:52:12.504812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e230655523'
down_revision = 'd0a4996f1eb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_asset', sa.Float(), nullable=True),
    sa.Column('passive_liability', sa.Float(), nullable=True),
    sa.Column('total_assets', sa.Float(), nullable=True),
    sa.Column('third_party_liability', sa.Float(), nullable=True),
    sa.Column('financial_obligations', sa.Float(), nullable=True),
    sa.Column('net_sales', sa.Float(), nullable=True),
    sa.Column('gross_utility', sa.Float(), nullable=True),
    sa.Column('net_utility', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'not_approved', name='analysisstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis')
    # ### end Alembic commands ###
