"""empty message

Revision ID: e102cfab9558
Revises: a2e230655523
Create Date: 2017-11-05 19:52:45.101813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e102cfab9558'
down_revision = 'a2e230655523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('entity_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'analysis', 'entity', ['entity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analysis', type_='foreignkey')
    op.drop_column('analysis', 'entity_id')
    # ### end Alembic commands ###
